$ANSIBLE_VAULT;1.1;AES256
30376537363439323062393466646462393663376238643237623436643137626566643861366331
3838643939346138336134383865656235333562306134330a623832646530383334613833373462
30393631343431303234663861643037656432643237373761623266333338306363663233393237
6466613238643735360a386639636630373039313633323531393864376465313035633562353731
62636332333566313733633037323866373335663634336130383734646638666436323137353363
62353465313364636332303034626166626630316461393437336137376333616263373464303930
64386336643462386439623435613433336632373232303565386237336561363736346532316539
37653834326461383666626336646266363365613939656236343263333965343433616136396534
63326338663930353933356438343962656561653039366335646464306533346533353231656131
37613234363337656435613439396463306236613761393866656633393235616434633139386562
63303332613632616139353862383936383964396566346539333038666531663031643431303561
38363564656139663337666635613032666436353938353133356162656163616630386431396530
3033
