---
controller_configuration_projects_secure_logging: true
controller_configuration_projects_async_retries: 15
controller_configuration_projects_async_delay: 5

controller_projects:
- name: dtech2026
  description: Distributech 2026 demo project
  organization: vpacalliance
  scm_type: git
  scm_url: https://github.com/rprakashg-rh/vpac-dtech-2026.git
  scm_branch: main
  state: present
...
