---
# hosts allocated for distrbutech 2026 demos for vpac alliance organization
controller_hosts:
- name: dtech2026dell1
  inventory: DTECH2026 Inventory
  variables:
    ansible_host: 192.168.100.51
    ansible_port: 22
  enabled: true

- name: dtech2026dell2
  inventory: DTECH2026 Inventory
  variables:
    ansible_host: 192.168.100.52
    ansible_port: 22
  enabled: true

- name: dtech2026advantech
  inventory: DTECH2026 Inventory
  variables:
    ansible_host: 192.168.100.53
    ansible_port: 22
  enabled: true
