---
- name: Ansible playbook that configures virtualization hosts to deploy SSC600 SW
  hosts: virtualization_hosts
  gather_facts: yes

  tasks:
  - name: Load ansible vault
    ansible.builtin.include_vars:
      file: "./vars/secrets.yml"

  - name: Configure the system for running realtime workloads
    ansible.builtin.import_role:
      name: rprakashg.vpac.prepare_system_for_rt
    vars:
      processbus_nic: "{{ networking.processbus.nic }}"