# This playbook configures a RHEL host as imagebuilder server
---
- name: Run osbuild_server role
  hosts: imagebuilder
  gather_facts: yes
  
  tasks:
  - name: Import role
    ansible.builtin.import_role:
      name: rprakashg.vpac.setup_imagebuilder